version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_measures:
    run: ehrql:v1 generate-measures --output output/patient_measures/winter_pressure_measures.csv.gz analysis/measures_definition.py
    outputs:
      highly_sensitive:
        dataset: output/patient_measures/winter_pressure_measures.csv.gz
  generate_practice_measures:
    run: python:latest analysis/practice_measures.py 
        --output output/practice_measures/practice_measures.csv.gz
        --output output/patient_measures/processed_measures.csv.gz
        --output output/patient_measures/frequency_table.csv.gz
    needs: [generate_measures]
    outputs:
      highly_sensitive:
        practice_measure: output/practice_measures/practice_measures.csv.gz
        patient_measure: output/patient_measures/processed_measures.csv.gz
        frequency_table: output/patient_measures/frequency_table.csv.gz
  generate_measures_viz:
    run: r:latest analysis/viz_measures.r
        --output output/total_measures/total_app.png
    needs: [generate_practice_measures]
    outputs:
      moderately_sensitive:
        app_figures: output/*/*.png

