version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_measures:
    run: ehrql:v1 generate-measures --output output/patient_measures/winter_pressure_measures.csv.gz analysis/measures_definition.py
    outputs:
      highly_sensitive:
        dataset: output/patient_measures/winter_pressure_measures.csv.gz
  generate_app_measures:
    run: ehrql:v1 generate-measures --output output/appointments/app_measures.csv analysis/appointments/app_measures.py
    outputs:
      moderately_sensitive:
        dataset: output/appointments/app_measures.csv
  generate_app_viz:
    run: r:latest analysis/appointments/app_viz.r
    needs: [generate_app_measures]
    outputs:
      moderately_sensitive:
        app_figures: output/appointments/*.png
  generate_app_summary:
    run: python:latest analysis/appointments/app_summary.py
    needs: [generate_app_measures]
    outputs:
      moderately_sensitive:
        app_table: output/appointments/app_summary.csv
  generate_pre_processing:
    run: python:latest analysis/pre_processing.py 
        --output output/practice_measures/practice_measures.csv.gz
        --output output/patient_measures/processed_measures.csv.gz
        --output output/patient_measures/frequency_table.csv
    needs: [generate_measures]
    outputs:
      highly_sensitive:
        practice_measure: output/practice_measures/practice_measures.csv.gz
        patient_measure: output/patient_measures/processed_measures.csv.gz
      moderately_sensitive:
        frequency_table: output/patient_measures/frequency_table.csv
  generate_measures_viz:
    run: r:latest analysis/viz_measures.r
    needs: [generate_pre_processing]
    outputs:
      moderately_sensitive:
        app_figures: output/*/*.png
        total_measures: output/total_measures/*.csv

