version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_measures:
    run: ehrql:v1 generate-measures --output output/patient_measures/winter_pressure_measures.csv.gz analysis/measures_definition.py
    outputs:
      highly_sensitive:
        dataset: output/patient_measures/winter_pressure_measures.csv.gz
