version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_measures:
    run: ehrql:v1 generate-measures --output output/dataset_measures.csv.gz analysis/dataset_definition_measures.py
    outputs:
      highly_sensitive:
        dataset: output/dataset_measures.csv.gz
