version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_patient_measures:
    run: ehrql:v1 generate-measures --output output/patient_measures/patient_measures.csv.gz analysis/wp_patient_measures_def.py -- --drop_reason --drop_prescriptions --drop_indicat_prescript
    outputs:
       highly_sensitive:
         dataset: output/patient_measures/patient_measures.csv.gz
  #generate_practice_measures_keep_follow_up:
  #  run: ehrql:v1 generate-measures --output output/practice_measures/practice_measures_keep_follow_up.csv.gz analysis/wp_practice_measures_def.py -- --drop_reason --drop_prescriptions --drop_indicat_prescript
  #  outputs:
  #    highly_sensitive:
  #      dataset: output/practice_measures/practice_measures_keep_follow_up.csv.gz
  #generate_practice_measures_keep_reason:
  #  run: ehrql:v1 generate-measures --output output/practice_measures/practice_measures_keep_reason.csv.gz analysis/wp_practice_measures_def.py -- --drop_follow_up --drop_prescriptions --drop_indicat_prescript
  #  outputs:
  #    highly_sensitive:
  #      dataset: output/practice_measures/practice_measures_keep_reason.csv.gz
  #generate_practice_measures_keep_prescriptions:
  #  run: ehrql:v1 generate-measures --output output/practice_measures/practice_measures_keep_prescriptions.csv.gz analysis/wp_practice_measures_def.py -- --drop_follow_up --drop_reason --drop_indicat_prescript
  #  outputs:
  #    highly_sensitive:
  #      dataset: output/practice_measures/practice_measures_keep_prescriptions.csv.gz
  #generate_practice_measures_keep_indicat_prescript:
  #  run: ehrql:v1 generate-measures --output output/practice_measures/practice_measures_keep_indicat_prescript.csv.gz analysis/wp_practice_measures_def.py -- --drop_follow_up --drop_reason --drop_prescriptions
  #  outputs:
  #    highly_sensitive:
  #      dataset: output/practice_measures/practice_measures_keep_indicat_prescript.csv.gz
  generate_practice_measures:
    run: ehrql:v1 generate-measures --output output/practice_measures/practice_measures.csv.gz analysis/wp_practice_measures_def.py -- --drop_reason --drop_prescriptions --drop_indicat_prescript
    outputs:
      highly_sensitive:
        dataset: output/practice_measures/practice_measures.csv.gz
  generate_app_measures_intv_1:
     run: ehrql:v1 generate-measures --output output/appointments/app_measures.csv analysis/appointments/app_measures.py -- --start_intv 2023-07-01
     outputs:
       moderately_sensitive:
         dataset: output/appointments/app_measures_1.csv
  generate_app_measures_intv_2:
     run: ehrql:v1 generate-measures --output output/appointments/app_measures.csv analysis/appointments/app_measures.py -- --start_intv 2023-12-01
     outputs:
       moderately_sensitive:
         dataset: output/appointments/app_measures_2.csv
  generate_app_measures_intv_3:
    run: ehrql:v1 generate-measures --output output/appointments/app_measures.csv analysis/appointments/app_measures.py -- --start_intv 2018-07-01
    outputs:
      moderately_sensitive:
        dataset: output/appointments/app_measures_3.csv
  generate_app_measures_intv_4:
    run: ehrql:v1 generate-measures --output output/appointments/app_measures.csv analysis/appointments/app_measures.py -- --start_intv 2018-12-01
    outputs:
      moderately_sensitive:
        dataset: output/appointments/app_measures_4.csv
  # generate_app_viz:
  #   run: r:latest analysis/appointments/app_viz.r
  #   needs: [generate_app_measures]
  #   outputs:
  #     moderately_sensitive:
  #       app_figures: output/appointments/*.png
  generate_app_pivot_table:
      run: r:latest analysis/appointments/app_pivot_table.r
      outputs:
        moderately_sensitive:
          app_pivot_table: output/appointments/status_summary.csv
  # generate_pre_processing:
  #   run: python:latest analysis/pre_processing.py 
  #       --output output/practice_measures/processed_practice_measures.csv.gz
  #       --output output/patient_measures/processed_patient_measures.csv.gz
  #       --output output/patient_measures/frequency_table.csv
  #   needs: [generate_patient_measures, generate_practice_measures]
  #   outputs:
  #     highly_sensitive:
  #       practice_measure: output/practice_measures/processed_practice_measures.csv.gz
  #       patient_measure: output/patient_measures/processed_patient_measures.csv.gz
  #     moderately_sensitive:
  #       frequency_table: output/patient_measures/frequency_table.csv
  # generate_measures_viz:
  #   run: r:latest analysis/viz_measures.r
  #   needs: [generate_pre_processing]
  #   outputs:
  #     moderately_sensitive:
  #       app_figures: output/*/*.png
  #       total_measures: output/total_measures/*.csv
  # generate_test_data:
  #   run: ehrql:v1 generate-dataset analysis/dataset.py --output output/patient_measures/test.csv --test-data-file analysis/test_dataset.py
  #   outputs:
  #     highly_sensitive:
  #       dataset: output/patient_measures/test.csv

