
version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_patient_measures_2016-08-10:
    run: ehrql:v1 generate-measures analysis/wp_measures.py
      --output output/patient_measures/patient_measures_2016-08-10.csv.gz
      --
      --patient_measures
      --start_intv 2016-08-10
    outputs:
      highly_sensitive:
        dataset: output/patient_measures/patient_measures_2016-08-10.csv.gz

  generate_patient_measures_2017-08-09:
    run: ehrql:v1 generate-measures analysis/wp_measures.py
      --output output/patient_measures/patient_measures_2017-08-09.csv.gz
      --
      --patient_measures
      --start_intv 2017-08-09
    outputs:
      highly_sensitive:
        dataset: output/patient_measures/patient_measures_2017-08-09.csv.gz

  generate_patient_measures_2018-08-08:
    run: ehrql:v1 generate-measures analysis/wp_measures.py
      --output output/patient_measures/patient_measures_2018-08-08.csv.gz
      --
      --patient_measures
      --start_intv 2018-08-08
    outputs:
      highly_sensitive:
        dataset: output/patient_measures/patient_measures_2018-08-08.csv.gz

  generate_patient_measures_2019-08-07:
    run: ehrql:v1 generate-measures analysis/wp_measures.py
      --output output/patient_measures/patient_measures_2019-08-07.csv.gz
      --
      --patient_measures
      --start_intv 2019-08-07
    outputs:
      highly_sensitive:
        dataset: output/patient_measures/patient_measures_2019-08-07.csv.gz

  generate_patient_measures_2020-08-05:
    run: ehrql:v1 generate-measures analysis/wp_measures.py
      --output output/patient_measures/patient_measures_2020-08-05.csv.gz
      --
      --patient_measures
      --start_intv 2020-08-05
    outputs:
      highly_sensitive:
        dataset: output/patient_measures/patient_measures_2020-08-05.csv.gz

  generate_patient_measures_2021-08-04:
    run: ehrql:v1 generate-measures analysis/wp_measures.py
      --output output/patient_measures/patient_measures_2021-08-04.csv.gz
      --
      --patient_measures
      --start_intv 2021-08-04
    outputs:
      highly_sensitive:
        dataset: output/patient_measures/patient_measures_2021-08-04.csv.gz

  generate_patient_measures_2022-08-03:
    run: ehrql:v1 generate-measures analysis/wp_measures.py
      --output output/patient_measures/patient_measures_2022-08-03.csv.gz
      --
      --patient_measures
      --start_intv 2022-08-03
    outputs:
      highly_sensitive:
        dataset: output/patient_measures/patient_measures_2022-08-03.csv.gz

  generate_patient_measures_2023-08-02:
    run: ehrql:v1 generate-measures analysis/wp_measures.py
      --output output/patient_measures/patient_measures_2023-08-02.csv.gz
      --
      --patient_measures
      --start_intv 2023-08-02
    outputs:
      highly_sensitive:
        dataset: output/patient_measures/patient_measures_2023-08-02.csv.gz

  generate_practice_measures_2016-08-10:
    run: ehrql:v1 generate-measures analysis/wp_measures.py
      --output output/practice_measures/practice_measures_2016-08-10.csv.gz
      --
      --practice_measures
      --start_intv 2016-08-10
    outputs:
      highly_sensitive:
        dataset: output/practice_measures/practice_measures_2016-08-10.csv.gz

  generate_practice_measures_2017-08-09:
    run: ehrql:v1 generate-measures analysis/wp_measures.py
      --output output/practice_measures/practice_measures_2017-08-09.csv.gz
      --
      --practice_measures
      --start_intv 2017-08-09
    outputs:
      highly_sensitive:
        dataset: output/practice_measures/practice_measures_2017-08-09.csv.gz

  generate_practice_measures_2018-08-08:
    run: ehrql:v1 generate-measures analysis/wp_measures.py
      --output output/practice_measures/practice_measures_2018-08-08.csv.gz
      --
      --practice_measures
      --start_intv 2018-08-08
    outputs:
      highly_sensitive:
        dataset: output/practice_measures/practice_measures_2018-08-08.csv.gz

  generate_practice_measures_2019-08-07:
    run: ehrql:v1 generate-measures analysis/wp_measures.py
      --output output/practice_measures/practice_measures_2019-08-07.csv.gz
      --
      --practice_measures
      --start_intv 2019-08-07
    outputs:
      highly_sensitive:
        dataset: output/practice_measures/practice_measures_2019-08-07.csv.gz

  generate_practice_measures_2020-08-05:
    run: ehrql:v1 generate-measures analysis/wp_measures.py
      --output output/practice_measures/practice_measures_2020-08-05.csv.gz
      --
      --practice_measures
      --start_intv 2020-08-05
    outputs:
      highly_sensitive:
        dataset: output/practice_measures/practice_measures_2020-08-05.csv.gz

  generate_practice_measures_2021-08-04:
    run: ehrql:v1 generate-measures analysis/wp_measures.py
      --output output/practice_measures/practice_measures_2021-08-04.csv.gz
      --
      --practice_measures
      --start_intv 2021-08-04
    outputs:
      highly_sensitive:
        dataset: output/practice_measures/practice_measures_2021-08-04.csv.gz

  generate_practice_measures_2022-08-03:
    run: ehrql:v1 generate-measures analysis/wp_measures.py
      --output output/practice_measures/practice_measures_2022-08-03.csv.gz
      --
      --practice_measures
      --start_intv 2022-08-03
    outputs:
      highly_sensitive:
        dataset: output/practice_measures/practice_measures_2022-08-03.csv.gz

  generate_practice_measures_2023-08-02:
    run: ehrql:v1 generate-measures analysis/wp_measures.py
      --output output/practice_measures/practice_measures_2023-08-02.csv.gz
      --
      --practice_measures
      --start_intv 2023-08-02
    outputs:
      highly_sensitive:
        dataset: output/practice_measures/practice_measures_2023-08-02.csv.gz

  generate_app_measures_intv_1:
     run: ehrql:v1 generate-measures analysis/appointments/app_measures.py
      --output output/appointments/app_measures_1.csv 
      -- 
      --start_intv 2023-07-01
     outputs:
       moderately_sensitive:
         dataset: output/appointments/app_measures_1.csv
 
  generate_app_measures_intv_2:
     run: ehrql:v1 generate-measures analysis/appointments/app_measures.py
      --output output/appointments/app_measures_2.csv 
      -- 
      --start_intv 2023-12-01
     outputs:
       moderately_sensitive:
         dataset: output/appointments/app_measures_2.csv
 
  generate_app_measures_intv_3:
     run: ehrql:v1 generate-measures analysis/appointments/app_measures.py
      --output output/appointments/app_measures_3.csv 
      -- 
      --start_intv 2018-07-01
     outputs:
       moderately_sensitive:
         dataset: output/appointments/app_measures_3.csv
 
  generate_app_measures_intv_4:
     run: ehrql:v1 generate-measures analysis/appointments/app_measures.py
      --output output/appointments/app_measures_4.csv 
      -- 
      --start_intv 2018-12-01
     outputs:
       moderately_sensitive:
         dataset: output/appointments/app_measures_4.csv
 
  generate_app_processing:
     run: r:latest analysis/appointments/app_processing.r
     needs: [generate_app_measures_intv_1, generate_app_measures_intv_2, generate_app_measures_intv_3, generate_app_measures_intv_4]
     outputs:
       moderately_sensitive:
         table_rounded: output/appointments/app_measures_rounded_*.csv
         table_pivot: output/appointments/app_pivot_table_*.csv

  generate_pre_processing:
    run: python:latest test.py 
        --output output/practice_measures/processed_practice_measures.csv.gz
        --output output/patient_measures/processed_patient_measures.csv.gz
        --output output/patient_measures/frequency_table.csv
    outputs:
      highly_sensitive:
        practice_measure: output/practice_measures/processed_practice_measures.csv.gz
        patient_measure: output/patient_measures/processed_patient_measures.csv.gz
      moderately_sensitive:
        frequency_table: output/patient_measures/frequency_table.csv
  generate_tables:
    run: r:latest analysis/table_generation.r
    needs: [generate_pre_processing]
    outputs:
      moderately_sensitive:
        total_measures: output/total_measures/*.csv
        practice_measures: output/practice_measures/*.csv
        patient_measures: output/patient_measures/*.csv
